attn_dropout: 0.0
batch_size: 32
drop_last_loader: false
dropout: 0.1
enable_progress_bar: true
futr_exog_list:
- trend
h: 12
hidden_size: 20
hist_exog_list:
- y_[lag12]
input_size: 48
learning_rate: 0.01
loss: !!python/object:neuralforecast.losses.pytorch.DistributionLoss
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _base_distribution: !!python/name:torch.distributions.studentT.StudentT ''
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - []
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - - - quantiles
      - !!python/object/apply:torch._utils._rebuild_parameter
        - !!python/object/apply:torch._utils._rebuild_tensor_v2
          - !!python/object/apply:torch.storage._load_from_bytes
            - !!binary |
              gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
              AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
              aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
              Z2UKcQFYDQAAADI0MjcyODA4NzI2NTZxAlgDAAAAY3B1cQNLBU50cQRRLoACXXEAWA0AAAAyNDI3
              MjgwODcyNjU2cQFhLgUAAAAAAAAAAAAAP83MTD3NzMw9ZmZmPzMzcz8=
          - 0
          - !!python/tuple
            - 5
          - !!python/tuple
            - 1
          - false
          - !!python/object/apply:collections.OrderedDict
            - []
        - false
        - !!python/object/apply:collections.OrderedDict
          - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  domain_map: !!python/name:neuralforecast.losses.pytorch.student_domain_map ''
  is_distribution_output: true
  num_samples: 500
  output_names:
  - -median
  - -lo-90.0
  - -lo-80.0
  - -hi-80.0
  - -hi-90.0
  outputsize_multiplier: 3
  param_names:
  - -df
  - -loc
  - -scale
  return_params: false
  training: true
max_epochs: 200
max_steps: 200
n_head: 4
num_workers_loader: 0
random_seed: 1
scaler_type: robust
stat_exog_list:
- airline1
step_size: 1
tgt_size: 1
windows_batch_size: null
